/**
 * MODULE: First-run bootstrap
 *
 * Purpose        Take a freshly cloned checkout to a runnable application
 *                without the operator knowing anything about Prisma or .env.
 * Responsibility Create configuration, apply migrations, and seed once.
 * Dependencies   node:fs, node:crypto, node:child_process, @prisma/client.
 *
 * Safe to run repeatedly. Every step checks whether it has already been done:
 * an existing `.env` is never overwritten (that would rotate SESSION_SECRET and
 * sign everybody out), and seeding is skipped once any centre exists (that
 * would be a silent no-op at best and duplicate history at worst).
 *
 * Invoked by start-edutrack.bat and available as `npm run setup`.
 */

import { execSync } from "node:child_process";
import { randomBytes } from "node:crypto";
import { existsSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const projectRoot = join(dirname(fileURLToPath(import.meta.url)), "..");
const envPath = join(projectRoot, ".env");

function run(command) {
  execSync(command, { cwd: projectRoot, stdio: "inherit" });
}

function secret(bytes) {
  return randomBytes(bytes).toString("base64url");
}

function createEnvFile() {
  const contents = [
    "# Generated by scripts/bootstrap.mjs on first run.",
    "# Local development uses SQLite so no database server is needed.",
    "# See docs/DEPLOYMENT.md to switch to PostgreSQL for production.",
    "",
    'DATABASE_URL="file:./dev.db"',
    `SESSION_SECRET="${secret(48)}"`,
    'SESSION_TTL_HOURS="720"',
    'NODE_ENV="development"',
    'APP_URL="http://localhost:3000"',
    "",
    "# CONSOLE logs notifications instead of sending them, so nobody is",
    "# messaged from a local machine. See docs/DEPLOYMENT.md for WhatsApp.",
    'NOTIFICATION_CHANNEL="CONSOLE"',
    `CRON_SECRET="${secret(32)}"`,
    "",
    "# Password-reset emails. CONSOLE prints them to this window, reset link",
    "# included, so the flow works with no provider account.",
    'EMAIL_CHANNEL="CONSOLE"',
    "",
    "# Google Sign-In is optional. Without it the button is simply not shown.",
    "# Add an OAuth Client ID and list this app's origin under",
    '# "Authorized JavaScript origins". There is no client secret to set.',
    '# GOOGLE_CLIENT_ID="000000000000-xxxxxxxx.apps.googleusercontent.com"',
    "",
  ].join("\n");

  writeFileSync(envPath, contents, { encoding: "utf8", flag: "wx" });
}

async function centreCount() {
  // Imported lazily: the Prisma client does not exist until `generate` has run.
  const { PrismaClient } = await import("@prisma/client");
  const db = new PrismaClient();
  try {
    return await db.centre.count();
  } finally {
    await db.$disconnect();
  }
}

async function main() {
  if (existsSync(envPath)) {
    console.log("[1/4] Configuration found — keeping your existing .env");
  } else {
    console.log("[1/4] Creating .env with freshly generated secrets");
    createEnvFile();
  }

  console.log("[2/4] Generating the database client");
  run("npx prisma generate");

  console.log("[3/4] Applying database migrations");
  run("npx prisma migrate deploy");

  const existingCentres = await centreCount();

  if (existingCentres > 0) {
    console.log(`[4/4] Database already has ${existingCentres} centre(s) — skipping seed`);
  } else {
    console.log("[4/4] Empty database — loading demo data (this takes a minute)");
    run("npm run db:seed");
  }

  console.log("\nReady.");
}

main().catch((error) => {
  console.error("\nSetup failed:", error.message ?? error);
  process.exit(1);
});
